version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      nuget:
        patterns: ["*"]
    labels: ["dependency"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    labels: ["dependency"]

  - package-ecosystem: dotnet-sdk
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependency"]
